Add the ring relabelling notebooks and associated output
WatChPhoto/PhotogrammetryAnalysis pull request #11
Opened 2021-03-22 20:13 UTC by nickwp

This adds the ring relabelling notebooks. Commits from Michael's [fork](https://github.com/msekatchev/PhotogrammetryAnalysis) are also included since that's where I was working from.
Merging this as it is maybe not the nicest before tidying up, but I think worth being able to tag the version as presented to SK on 18th March.

2021-03-25 14:10 UTC, pdeperio requested changes
please remove (large) binaries, like photos (`*.jpg`) and output figures (`*.png`)

2021-03-26 00:57 UTC, nickwp commented
I removed the image files... although the notebooks are actually ~200x larger than the images, which were only ~60kb each

2021-05-03 19:06 UTC, pdeperio approved these changes

2021-05-03 19:11 UTC, msekatchev approved these changes

2021-05-12 22:51 UTC, merged